# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # boxIp = "192.168.50.53"

    config.vm.box = "francodacosta/symfony"

    # config.vm.network :private_network, ip: boxIp

    config.vm.synced_folder "./code", "/var/www/html/symfony" #, type:"nfs"

    config.vm.provider :virtualbox do |vb|
        vb.gui = false
        config.vbguest.auto_update = true
        vb.customize ["modifyvm", :id, "--memory", "2048", "--cpuexecutioncap", "90"]
    end

    config.vm.provision "ansible" do |ansible|
        ansible.limit = 'all'
        ansible.playbook = "./playbook.yml"
    end
end
